/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    packages: Package;
    workshops: Workshop;
    testimonials: Testimonial;
    faqs: Faq;
    media: Media;
    orders: Order;
    submissions: Submission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    workshops: WorkshopsSelect<false> | WorkshopsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Articolele de pe blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Se completează singur din titlu, fără diacritice. Îl poți edita, dar după publicare schimbarea rupe linkurile existente.
   */
  slug: string;
  /**
   * Maximum 200 de caractere. Apare în cardul de articol, în meta description și în RSS.
   */
  excerpt: string;
  /**
   * Raport 16:9. Fără imagine, cardul afișează un placeholder crem.
   */
  cover?: (number | null) | Media;
  category: number | Category;
  /**
   * Data afișată pe articol și folosită la sortare.
   */
  publishedAt: string;
  /**
   * Calculat automat din conținut la fiecare salvare.
   */
  readingTime?: number | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Opțional. Dacă completezi, articolul primește schema FAQPage — răspunsurile pot apărea direct în Google și în răspunsurile AI.
   */
  faq?:
    | {
        question: string;
        /**
         * Text simplu, fără formatare. Primele două fraze contează cel mai mult.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opțional. Gol = se completează automat din aceeași categorie.
   */
  relatedPosts?: (number | Post)[] | null;
  /**
   * Lasă gol ca să se folosească titlul și descrierea documentului.
   */
  seo?: {
    /**
     * Ideal sub 60 de caractere. Gol = titlul documentului.
     */
    metaTitle?: string | null;
    /**
     * Ideal 150–160 de caractere. Gol = rezumatul documentului.
     */
    metaDescription?: string | null;
    /**
     * Gol = imaginea implicită din Setările site-ului.
     */
    ogImage?: (number | null) | Media;
    /**
     * Adaugă `noindex`. Pagina rămâne accesibilă prin link direct.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imaginile și fișierele folosite pe site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Ce se vede în imagine, într-o frază. Îl citesc cititoarele de ecran și motoarele de căutare. Obligatoriu.
   */
  alt: string;
  /**
   * Opțional. Apare sub imagine, acolo unde designul prevede legendă.
   */
  caption?: string | null;
  /**
   * Opțional. Numele fotografului sau sursa licenței.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categoriile în care se împart articolele de blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Se completează singur din titlu, fără diacritice. Îl poți edita, dar după publicare schimbarea rupe linkurile existente.
   */
  slug: string;
  /**
   * O frază despre ce găsește cititorul aici. Apare pe pagina categoriei și în meta description.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pachetele de consultanță, cu prețurile pe care le vede clientul.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  /**
   * Se completează singur din titlu, fără diacritice. Îl poți edita, dar după publicare schimbarea rupe linkurile existente.
   */
  slug: string;
  /**
   * Apare sub numele pachetului, pe card.
   */
  tagline?: string | null;
  forWho?: string | null;
  /**
   * Punctele din listă, în ordinea în care vrei să fie citite.
   */
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * De exemplu: „4 sesiuni · 6 săptămâni".
   */
  duration?: string | null;
  format?: ('online' | 'fata-in-fata' | 'hibrid') | null;
  /**
   * În lei, fără separator de mii: scrie 5100, nu 5.100. Se citește doar pe server. La salvare, prețul se trimite automat în Stripe.
   */
  price?: number | null;
  /**
   * Bifat: prețul nu se afișează pe site și nu se poate plăti online. În locul lui apare butonul „Solicită ofertă", care duce la formularul de contact, cu mesajul precompletat.
   */
  priceOnRequest?: boolean | null;
  /**
   * Numere mai mici apar primele.
   */
  order: number;
  /**
   * Un singur pachet, în designul aprobat cel din mijloc.
   */
  featured?: boolean | null;
  /**
   * Debifează pentru a ascunde pachetul fără a-l șterge.
   */
  active?: boolean | null;
  /**
   * Apare pe pagina dedicată pachetului.
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lasă gol ca să se folosească titlul și descrierea documentului.
   */
  seo?: {
    /**
     * Ideal sub 60 de caractere. Gol = titlul documentului.
     */
    metaTitle?: string | null;
    /**
     * Ideal 150–160 de caractere. Gol = rezumatul documentului.
     */
    metaDescription?: string | null;
    /**
     * Gol = imaginea implicită din Setările site-ului.
     */
    ogImage?: (number | null) | Media;
    /**
     * Adaugă `noindex`. Pagina rămâne accesibilă prin link direct.
     */
    noIndex?: boolean | null;
  };
  stripeProductId?: string | null;
  stripePriceId?: string | null;
  stripeSyncStatus?: ('synced' | 'skipped' | 'error') | null;
  stripeSyncMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catalogul de workshopuri. Se pot cumpăra întotdeauna doar următoarele trei ediții cu dată în viitor — ca să deschizi un workshop la înscriere, dă-i o dată.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops".
 */
export interface Workshop {
  id: number;
  /**
   * Titlul creativ, cel care se vede primul. De exemplu: „Sub presiune".
   */
  title: string;
  /**
   * Se completează singur din titlu, fără diacritice. Îl poți edita, dar după publicare schimbarea rupe linkurile existente.
   */
  slug: string;
  /**
   * Competența, scrisă cum o caută oamenii în Google. Apare imediat sub titlu. De exemplu: „Inteligență emoțională și autoreglare în business".
   */
  subtitle: string;
  /**
   * Una-două fraze, singurul text vizibil înainte ca cineva să apese „Citește tot programul". Scrie-o ca să se înțeleagă singură, fără restul paginii.
   */
  summary: string;
  /**
   * Gol = workshopul apare în catalog, fără buton de plată. Cu dată în viitor, intră la rând: primele trei astfel de ediții sunt deschise la înscriere. Ora este întotdeauna 09:00–17:00.
   */
  sessionDate?: string | null;
  /**
   * Per participant, în lei. Se citește doar pe server. La salvare, prețul se trimite automat în Stripe.
   */
  price: number;
  /**
   * Ordinea firului logic al seriei, folosită pentru workshopurile FĂRĂ dată. Cele cu dată se așază singure, cronologic, deasupra lor.
   */
  order: number;
  /**
   * Debifează pentru a scoate workshopul din catalog fără a-l șterge.
   */
  active?: boolean | null;
  /**
   * Începe cu titlul workshopului și spune într-o frază ce este. Fraza asta e cea mai citată de motoarele de căutare și de asistenții AI.
   */
  what: string;
  /**
   * Situația concretă, în cuvintele omului care o trăiește.
   */
  problems: string;
  /**
   * Singura parte din „Cum se desfășoară" care diferă de la un workshop la altul. Restul e comun și apare o dată, sus.
   */
  workMethod: string;
  /**
   * Punctele din listă, în ordinea în care vrei să fie citite.
   */
  outcomes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * NU se afișează în pagină. Sunt notițe pentru redactare: expresiile pe care textul de mai sus ar trebui să le acopere natural. O listă lipită în pagină ar fi keyword stuffing și se penalizează.
   */
  keywords?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lasă gol ca să se folosească titlul și descrierea documentului.
   */
  seo?: {
    /**
     * Ideal sub 60 de caractere. Gol = titlul documentului.
     */
    metaTitle?: string | null;
    /**
     * Ideal 150–160 de caractere. Gol = rezumatul documentului.
     */
    metaDescription?: string | null;
    /**
     * Gol = imaginea implicită din Setările site-ului.
     */
    ogImage?: (number | null) | Media;
    /**
     * Adaugă `noindex`. Pagina rămâne accesibilă prin link direct.
     */
    noIndex?: boolean | null;
  };
  stripeProductId?: string | null;
  stripePriceId?: string | null;
  stripeSyncStatus?: ('synced' | 'skipped' | 'error') | null;
  stripeSyncMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recomandările primite de la oameni cu care Adriana a lucrat. Se publică integral, cu acordul scris al autorului.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Așa cum a cerut persoana să fie scris, cu titluri cu tot.
   */
  author: string;
  /**
   * Ancora recomandării pe pagina /testimoniale. Se completează singură din nume.
   */
  slug: string;
  /**
   * Ce dă greutate recomandării. De exemplu: „Director general, AGRO MARUS SRL". Lasă gol dacă autorul nu și-a trecut una — nu o completa din presupunere.
   */
  role?: string | null;
  /**
   * Scurt și factual. De exemplu: „Mentorat individual, 2021–2023". Gol = nu se afișează.
   */
  context?: string | null;
  /**
   * COPIAZĂ o frază întreagă din textul de mai jos, nu o rescrie și nu o tăia la mijloc. Apare pe prima pagină, între ghilimele, sub numele autorului — cine o citește trebuie să o regăsească în textul integral.
   */
  excerpt: string;
  /**
   * Un rând pentru fiecare paragraf, exact ca în textul primit. Nu se rescrie și nu se scurtează: e textul altcuiva.
   */
  paragraphs: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Secțiunea de pe prima pagină arată maximum trei recomandări. Textul integral rămâne oricum pe /testimoniale.
   */
  featured?: boolean | null;
  /**
   * Numere mai mici apar primele.
   */
  order: number;
  /**
   * Debifează dacă autorul își retrage acordul de publicare. Recomandarea rămâne în evidență, dar dispare de pe site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Întrebările afișate pe homepage și pe pagina de servicii.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Text simplu, fără formatare. Primele două fraze sunt cele care ajung în Google și în răspunsurile AI — pune concluzia la început.
   */
  answer: string;
  page: 'homepage' | 'servicii' | 'workshopuri' | 'ambele';
  /**
   * Numere mai mici apar primele.
   */
  order: number;
  /**
   * Se afișează sub răspuns. Lasă titlul gol dacă întrebarea nu are tabel.
   */
  comparisonTable?: {
    /**
     * Nu se vede pe ecran, dar îl citesc cititoarele de ecran și motoarele de căutare. Gol = fără tabel.
     */
    caption?: string | null;
    columns?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    rows?:
      | {
          label: string;
          /**
           * Câte una pentru fiecare coloană, în aceeași ordine.
           */
          cells?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Comenzile plătite prin Stripe — pachete de consultanță și locuri la workshopuri. Se creează automat; nu se pot edita de aici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  stripeSessionId: string;
  stripePaymentIntentId?: string | null;
  itemType: 'pachet' | 'workshop';
  /**
   * Relația se poate rupe dacă pachetul e șters. Numele de mai jos rămâne.
   */
  package?: (number | null) | Package;
  /**
   * Relația se poate rupe dacă workshopul e șters. Numele de mai jos rămâne.
   */
  workshop?: (number | null) | Workshop;
  packageNameSnapshot: string;
  sessionDateSnapshot?: string | null;
  /**
   * La workshopuri, câte locuri au fost plătite într-o singură comandă.
   */
  quantity: number;
  /**
   * Totalul încasat, în unități întregi ale monedei.
   */
  amount: number;
  currency: string;
  customerName?: string | null;
  customerEmail: string;
  customerPhone?: string | null;
  status: 'paid' | 'refunded' | 'failed';
  /**
   * Păstrat pentru depanare și reconciliere.
   */
  rawEvent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mesajele trimise din formularul de contact. Se șterg automat după 12 luni.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  /**
   * Dovada consimțământului, așa cum a fost trimisă de formular.
   */
  consent: boolean;
  /**
   * Bifează după ce ai răspuns. Nu afectează termenul de ștergere.
   */
  handled?: boolean | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cine are acces în acest panou și cu ce drepturi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Administratorul vede tot, inclusiv comenzile și mesajele. Redactorul administrează doar conținutul editorial.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'workshops';
        value: number | Workshop;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  category?: T;
  publishedAt?: T;
  readingTime?: T;
  content?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedPosts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  forWho?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  duration?: T;
  format?: T;
  price?: T;
  priceOnRequest?: T;
  order?: T;
  featured?: T;
  active?: T;
  longDescription?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  stripeProductId?: T;
  stripePriceId?: T;
  stripeSyncStatus?: T;
  stripeSyncMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops_select".
 */
export interface WorkshopsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  summary?: T;
  sessionDate?: T;
  price?: T;
  order?: T;
  active?: T;
  what?: T;
  problems?: T;
  workMethod?: T;
  outcomes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        item?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  stripeProductId?: T;
  stripePriceId?: T;
  stripeSyncStatus?: T;
  stripeSyncMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  slug?: T;
  role?: T;
  context?: T;
  excerpt?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  page?: T;
  order?: T;
  comparisonTable?:
    | T
    | {
        caption?: T;
        columns?:
          | T
          | {
              label?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              label?: T;
              cells?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  itemType?: T;
  package?: T;
  workshop?: T;
  packageNameSnapshot?: T;
  sessionDateSnapshot?: T;
  quantity?: T;
  amount?: T;
  currency?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  status?: T;
  rawEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  consent?: T;
  handled?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Datele de contact, firma și conturile care apar pe tot site-ul.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Apare sub nume, în header și în schema Person.
   */
  role?: string | null;
  /**
   * De exemplu: „Claritate înainte de decizie.".
   */
  tagline?: string | null;
  /**
   * 1200×630. Se folosește unde pagina nu are imagine proprie.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Gol = footerul afișează un placeholder.
   */
  email?: string | null;
  phone?: string | null;
  city?: string | null;
  region?: string | null;
  country?: string | null;
  /**
   * De exemplu: „Răspund în maximum 24 de ore lucrătoare".
   */
  responseTime?: string | null;
  /**
   * Rândul scurt din footer.
   */
  availability?: string | null;
  /**
   * Se încarcă doar la click, niciodată automat — altfel ar fi un terț înainte de consimțământ.
   */
  bookingUrl?: string | null;
  /**
   * Adresele complete. Alimentează footerul și câmpul `sameAs` din schema Person.
   */
  socialLinks?:
    | {
        platform: 'LinkedIn' | 'Instagram' | 'Facebook' | 'YouTube' | 'TikTok';
        url: string;
        id?: string | null;
      }[]
    | null;
  companyLegalName?: string | null;
  cui?: string | null;
  regCom?: string | null;
  registeredAddress?: string | null;
  /**
   * Forma G-XXXXXXXXXX. Gol = Google Analytics nu se încarcă deloc. Oricum se încarcă doar după acordul vizitatorului.
   */
  ga4MeasurementId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textele de pe prima pagină, secțiune cu secțiune.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Rândul versal de deasupra titlului.
   */
  heroEyebrow?: string | null;
  /**
   * Trei rânduri, ca în design. Fiecare intră separat în pagină; poți schimba textul, nu și numărul lor.
   */
  heroHeadline?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  heroLead?: string | null;
  heroIntro?: string | null;
  heroPrimaryCta?: {
    label?: string | null;
    /**
     * O ancoră (#servicii) sau o rută (/servicii).
     */
    href?: string | null;
  };
  heroSecondaryCta?: {
    label?: string | null;
    /**
     * O ancoră (#servicii) sau o rută (/servicii).
     */
    href?: string | null;
  };
  heroBadges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Raportul este fixat de design, deci înlocuirea fotografiei nu mișcă pagina.
   */
  heroImage?: (number | null) | Media;
  problema: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    body?: string | null;
    signs?:
      | {
          index: string;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  metoda: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    body?: string | null;
    steps?:
      | {
          index: string;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pentruCine: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    aside?: string | null;
    segments?:
      | {
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  univers: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    body?: string | null;
    note?: string | null;
    items?:
      | {
          numeral: string;
          title: string;
          trademark?: boolean | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  despre: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    credentials?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    link?: {
      label?: string | null;
      /**
       * O ancoră (#servicii) sau o rută (/servicii).
       */
      href?: string | null;
    };
    portrait?: (number | null) | Media;
  };
  valori: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    values?:
      | {
          index: string;
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  citat?: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    /**
     * Împărțirea pe rânduri este parte din design. Păstrează numărul lor.
     */
    lines?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    attribution?: string | null;
  };
  servicii: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    intro?: string | null;
    reassurance?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    footerLink?: {
      label?: string | null;
      /**
       * O ancoră (#servicii) sau o rută (/servicii).
       */
      href?: string | null;
    };
  };
  blog: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    link?: {
      label?: string | null;
      /**
       * O ancoră (#servicii) sau o rută (/servicii).
       */
      href?: string | null;
    };
  };
  faq: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
  };
  cta: {
    /**
     * Debifează pentru a ascunde secțiunea, păstrându-i textul.
     */
    visible?: boolean | null;
    eyebrow: {
      text: string;
      ornament?: ('line' | 'pulse' | 'none') | null;
    };
    heading?: string | null;
    body?: string | null;
    ctaLink?: {
      label?: string | null;
      /**
       * O ancoră (#servicii) sau o rută (/servicii).
       */
      href?: string | null;
    };
    note?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Narațiunea, reperele profesionale și cele patru principii.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title?: string | null;
  lead?: string | null;
  /**
   * Povestea profesională, la persoana întâi.
   */
  narrative?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  portrait?: (number | null) | Media;
  /**
   * Formări, certificări, ani de experiență. Câte unul pe rând.
   */
  credentials?:
    | {
        text: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  principles?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lasă gol ca să se folosească titlul și descrierea documentului.
   */
  seo?: {
    /**
     * Ideal sub 60 de caractere. Gol = titlul documentului.
     */
    metaTitle?: string | null;
    /**
     * Ideal 150–160 de caractere. Gol = rezumatul documentului.
     */
    metaDescription?: string | null;
    /**
     * Gol = imaginea implicită din Setările site-ului.
     */
    ogImage?: (number | null) | Media;
    /**
     * Adaugă `noindex`. Pagina rămâne accesibilă prin link direct.
     */
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  role?: T;
  tagline?: T;
  defaultOgImage?: T;
  email?: T;
  phone?: T;
  city?: T;
  region?: T;
  country?: T;
  responseTime?: T;
  availability?: T;
  bookingUrl?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  companyLegalName?: T;
  cui?: T;
  regCom?: T;
  registeredAddress?: T;
  ga4MeasurementId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeadline?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroLead?: T;
  heroIntro?: T;
  heroPrimaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroBadges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroImage?: T;
  problema?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        body?: T;
        signs?:
          | T
          | {
              index?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  metoda?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        body?: T;
        steps?:
          | T
          | {
              index?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  pentruCine?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        aside?: T;
        segments?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  univers?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        body?: T;
        note?: T;
        items?:
          | T
          | {
              numeral?: T;
              title?: T;
              trademark?: T;
              body?: T;
              id?: T;
            };
      };
  despre?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        credentials?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        portrait?: T;
      };
  valori?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        values?:
          | T
          | {
              index?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  citat?:
    | T
    | {
        visible?: T;
        lines?:
          | T
          | {
              text?: T;
              id?: T;
            };
        attribution?: T;
      };
  servicii?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        intro?: T;
        reassurance?:
          | T
          | {
              text?: T;
              id?: T;
            };
        footerLink?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  blog?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  faq?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
      };
  cta?:
    | T
    | {
        visible?: T;
        eyebrow?:
          | T
          | {
              text?: T;
              ornament?: T;
            };
        heading?: T;
        body?: T;
        ctaLink?:
          | T
          | {
              label?: T;
              href?: T;
            };
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  narrative?: T;
  portrait?: T;
  credentials?:
    | T
    | {
        text?: T;
        detail?: T;
        id?: T;
      };
  principles?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}